### ISSUE TITLE
Where is database?

### ISSUE THREAD

**Issue by goofmint** [koraktor/gallerist#1]
Hi. I got a error message.

```
ActiveRecord::StatementInvalid - SQLite3::SQLException: no such column: type: SELECT "RKVersion"."masterId", "RKVersion"."modelId", "RKVersion"."fileName", "RKVersion"."imageDate", type, "RKVersion"."uuid" FROM "RKVersion"  ORDER BY "RKVersion"."imageDate" ASC:
```

I have no sqlite3 database. Give us a scheme file.

**Comment by koraktor** [comment]
The databases are part of the Photos library. They reside inside the `.photoslibrary` bundle in `Databases`. Currently the files `Library.apdb` and `ImageProxies.apdb` are used.

The problem is, that the database schemes throughout different library versions aren't the same. It seems that the `RKVersion` table is missing a column that exists in the libraries I used for testing. What kind of library do you use? Was it migrated from iPhoto or a new one? Or maybe even a native iPhoto library? The latter isn't fully supported yet.

**Comment by goofmint** [comment]
@koraktor 
Thanks for reply.

I'm using iPhoto version 9.6. But I wasn't looking for Library.apdb, only Library.data. And I can't find any ImageProxies.\* file. Like below.

![screenshot 2015-03-10 9 35 57](https://cloud.githubusercontent.com/assets/5709/6567331/163a986a-c709-11e4-8ce5-467e6b0336b0.png)

I use iPhoto from old version. Is it a problem, right?

**Comment by koraktor** [comment]
The `*.adpb` files should reside inside of the `Database` directory. I guess the database scheme of iPhoto is slightly different from Photos. I have yet to find some mechanism that will allow to switch database schemes (or model classes) during initial library setup.

**Comment by koraktor** [comment]
@moongift I just pushed [two commits](https://github.com/koraktor/gallerist/compare/491c700a915778662e2c3582dd3ffac4b730bd44...3506736de150584dcdbbbe0354c2778989174047) that try to improve compatibility with iPhoto libraries. Maybe you want to try again.

**Comment by goofmint** [comment]
@koraktor 
Great! I got the photos!

![screenshot 2015-03-11 14 53 46](https://cloud.githubusercontent.com/assets/5709/6591142/72215d12-c7fe-11e4-952d-717fca5b1572.png)

I'll introduce the gallerist on my blog in Japanese.

Thanks!

**Comment by koraktor** [comment]
You're welome. And thanks for the blog post.

But please note that iPhoto support is still preliminary.
